version: "3.8"
services:
  godaddy-dns:
    image: ghcr.io/devlincashman/ntsdns:latest
    container_name: ntsdns
    restart: unless-stopped
    environment:
      KEY: godaddy_api_key
      SECRET: godaddy_api_secret
      DOMAIN: example.com
      NAME: examplesubdomain
      FREQUENCY: 15 # This is how many minutes between checks, defaults to 15
      TYPE: A # Supports most DNS record types, defaults to A
